# Generated by Django 3.1 on 2022-01-28 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_auto_20220128_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='ORDER_ID', max_length=100, unique=True),
        ),
    ]
