# Generated by Django 3.1 on 2022-01-28 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_auto_20220128_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='prepaymentorder',
            name='city',
            field=models.TextField(null=True),
        ),
    ]
