# Generated by Django 3.1 on 2022-01-29 22:23

from django.db import migrations, models
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_product_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='reference',
            field=models.UUIDField(default=store.models.generate_product_ref, unique=True),
        ),
    ]
