# Generated by Django 3.1 on 2022-01-29 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_auto_20220129_2223'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PrePaymentOrder',
        ),
    ]
