# Generated by Django 3.1 on 2022-01-29 22:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0017_delete_prepaymentorder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_id',
            new_name='paypal_order_id',
        ),
        migrations.AlterField(
            model_name='order',
            name='country',
            field=models.TextField(default='Portugal'),
        ),
        migrations.CreateModel(
            name='PrePaymentOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paypal_order_id', models.CharField(max_length=100, unique=True)),
                ('full_name', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=30)),
                ('city', models.TextField(null=True)),
                ('address_line_1', models.TextField()),
                ('address_line_2', models.TextField(blank=True, null=True)),
                ('postcode', models.TextField()),
                ('delivery_instructions', models.TextField(blank=True, null=True)),
                ('country', models.TextField(default='Portugal')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
