# Generated by Django 3.1 on 2022-01-30 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_auto_20220129_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basketitem',
            name='amount',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='amount',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
