# Generated by Django 3.1 on 2022-01-30 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_auto_20220130_0125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prepaymentorder',
            name='paypal_order_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
