# Generated by Django 3.1 on 2022-01-30 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paypal', '0005_auto_20220130_0159'),
        ('store', '0022_auto_20220130_0130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='paypal_order_id',
        ),
        migrations.AddField(
            model_name='order',
            name='paypal_order',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='paypal.paypalorder'),
        ),
    ]
