# Generated by Django 3.1 on 2022-02-03 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paypal', '0009_auto_20220203_0043'),
        ('store', '0023_auto_20220130_0216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='paypal_order',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order', to='paypal.paypalorder'),
        ),
    ]
