# Generated by Django 3.1 on 2022-01-30 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0019_auto_20220130_0009'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayPalMerchant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.EmailField(max_length=254)),
                ('merchant_id', models.TextField()),
                ('brand_name', models.CharField(max_length=127)),
            ],
        ),
        migrations.CreateModel(
            name='PayPalOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=30, unique=True)),
                ('order_status', models.TextField(choices=[('APPROVED', 'APPROVED'), ('CREATED', 'CREATED')], default='APPROVED')),
                ('payer_given_name', models.CharField(max_length=140)),
                ('payer_surname', models.TextField(blank=True, max_length=140, null=True)),
                ('payer_email_address', models.EmailField(max_length=254)),
                ('payer_id', models.CharField(max_length=13)),
                ('payer_country_code', models.CharField(blank=True, max_length=3, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PayPalShippingAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line_1', models.TextField(blank=True, null=True)),
                ('address_line_2', models.TextField(blank=True, null=True)),
                ('admin_area_2', models.TextField(blank=True, null=True)),
                ('admin_area_1', models.TextField(blank=True, null=True)),
                ('postal_code', models.TextField(blank=True, null=True)),
                ('country_code', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PayPalPurchaseUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_id', models.CharField(default='default', max_length=256)),
                ('currency_code', models.CharField(max_length=3)),
                ('value', models.DecimalField(decimal_places=2, max_digits=6)),
                ('merchant', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='paypal.paypalmerchant')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_units', to='paypal.paypalorder')),
                ('shipping', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='paypal.paypalshippingaddress')),
            ],
        ),
        migrations.CreateModel(
            name='PayPalItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField()),
                ('product', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.product')),
                ('purchase_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paypal.paypalpurchaseunit')),
            ],
        ),
    ]
