# Generated by Django 3.1 on 2022-01-30 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paypal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayPalPayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('given_name', models.CharField(max_length=140)),
                ('surname', models.TextField(blank=True, max_length=140, null=True)),
                ('email_address', models.EmailField(max_length=254)),
                ('paypal_id', models.CharField(max_length=13)),
                ('country_code', models.CharField(blank=True, max_length=3, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='paypalmerchant',
            old_name='merchant_id',
            new_name='paypal_id',
        ),
        migrations.RemoveField(
            model_name='paypalorder',
            name='payer_country_code',
        ),
        migrations.RemoveField(
            model_name='paypalorder',
            name='payer_email_address',
        ),
        migrations.RemoveField(
            model_name='paypalorder',
            name='payer_given_name',
        ),
        migrations.RemoveField(
            model_name='paypalorder',
            name='payer_id',
        ),
        migrations.RemoveField(
            model_name='paypalorder',
            name='payer_surname',
        ),
        migrations.AlterField(
            model_name='paypalorder',
            name='order_status',
            field=models.TextField(choices=[('COMPLETED', 'COMPLETED'), ('APPROVED', 'APPROVED'), ('CREATED', 'CREATED')], default='APPROVED'),
        ),
        migrations.AddField(
            model_name='paypalorder',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='paypal.paypalpayer'),
        ),
    ]
