# Generated by Django 3.1 on 2022-01-30 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paypal', '0002_auto_20220130_0117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paypalmerchant',
            name='paypal_id',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='paypalpayer',
            name='paypal_id',
            field=models.CharField(max_length=13, unique=True),
        ),
    ]
