# Generated by Django 3.1 on 2022-01-30 01:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('paypal', '0003_auto_20220130_0118'),
    ]

    operations = [
        migrations.AddField(
            model_name='paypalpayer',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paypal_payer', to=settings.AUTH_USER_MODEL),
        ),
    ]
