# Generated by Django 3.1 on 2022-01-30 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_auto_20220130_0130'),
        ('paypal', '0004_paypalpayer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paypalitem',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.product'),
        ),
    ]
