# Generated by Django 3.1 on 2022-01-30 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paypal', '0007_auto_20220130_0245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paypalitem',
            name='purchase_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='paypal.paypalpurchaseunit'),
        ),
    ]
