# Generated by Django 3.1 on 2022-02-03 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paypal', '0008_auto_20220130_0324'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paypalitem',
            options={'verbose_name': 'PayPal Sold Item', 'verbose_name_plural': 'PayPal Sold Items'},
        ),
        migrations.AlterModelOptions(
            name='paypalmerchant',
            options={'verbose_name': 'PayPal Merchant', 'verbose_name_plural': 'PayPal Merchants'},
        ),
        migrations.AlterModelOptions(
            name='paypalorder',
            options={'verbose_name': 'PayPal Order', 'verbose_name_plural': 'PayPal Orders'},
        ),
        migrations.AlterModelOptions(
            name='paypalpayer',
            options={'verbose_name': 'PayPal Payer', 'verbose_name_plural': 'PayPal Payers'},
        ),
        migrations.AlterModelOptions(
            name='paypalpurchaseunit',
            options={'verbose_name': 'PayPal Purchase Unit', 'verbose_name_plural': 'PayPal Purchase Units'},
        ),
        migrations.AlterModelOptions(
            name='paypalshippingaddress',
            options={'verbose_name': 'PayPal Shipping address', 'verbose_name_plural': 'PayPal Shipping addresses'},
        ),
    ]
